// Generates src/data/guides/models/bench-4.json — the 3D assembly model of the
// 4' bench (no back), read from public/downloads/guides/bench-4.pdf and the
// step drawings in public/img/guides/bench-4/. Run: node scripts/guide-models/bench-4.mjs
//
// Units inches; x = length (48), y = up (17), z = toward the viewer (18.5).
// Origin = centre of the footprint at ground level (see src/lib/guides3d/schema.ts).
//
// How the PDF builds it:
//   step 2  each end frame's first layer, laid flat: two B-4 (15.5") either side
//           of two B-5 (11.5") -> an 18.5" x 15.5" frame. Stood up, the B-4s are
//           the posts and the B-5s run across between them, top and bottom.
//   step 3  the second layer on top of the first: one B-3 (18.5") across the top
//           and four B-6 (8.5"): two along the bottom with a 1.5" gap between
//           them (the slot for B-2) and two up the sides. This layer faces inward.
//   step 4  B-2 (45") on edge in the slots at the base of both frames, screwed
//           through the outer B-5 into its ends (42" between frames + 2 x 1.5").
//   step 5  the front and back B-1 (48") top boards, flush with every edge.
//   step 6  the three middle B-1 boards with equal gaps (4 x 1/4").

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const T = 1.5; // 2x4 actual thickness
const W = 3.5; // 2x4 actual width
const LENGTH = 48;
const DEPTH = 18.5;
const FRAME_H = 15.5; // B-4 posts

const parts = [];
const counters = {};
function add(ref, size, position, step, extra = {}) {
  counters[ref] = (counters[ref] ?? 0) + 1;
  parts.push({ id: `${ref}#${counters[ref]}`, ref, kind: 'lumber', size, position, step, ...extra });
}
const r = (n) => Math.round(n * 1000) / 1000;

const xOuter = LENGTH / 2 - T / 2; // 23.25 — first layer, outside face flush with the top's ends
const xInner = LENGTH / 2 - T - T / 2; // 21.75 — second layer, facing inward
const zPost = DEPTH / 2 - W / 2; // 7.5

for (const side of [-1, 1]) {
  const out = side * xOuter;
  const inn = side * xInner;
  const away = [side * 30, 0, 0]; // first layer flies in from outside the bench
  const fromInside = [-side * 18, 0, 0]; // second layer is laid "on top" = from the inside

  // step 2 — first layer: B-4 posts and B-5 rails between them
  add('B-4', [T, FRAME_H, W], [out, FRAME_H / 2, -zPost], 2, { from: away });
  add('B-4', [T, FRAME_H, W], [out, FRAME_H / 2, zPost], 2, { from: away });
  add('B-5', [T, W, DEPTH - 2 * W], [out, W / 2, 0], 2, { from: away });
  add('B-5', [T, W, DEPTH - 2 * W], [out, FRAME_H - W / 2, 0], 2, { from: away });

  // step 3 — second layer: B-3 across the top, B-6 pair along the bottom with the
  // 1.5" slot between them, and a B-6 up each side
  add('B-3', [T, W, DEPTH], [inn, FRAME_H - W / 2, 0], 3, { from: fromInside });
  const slotHalf = T / 2;
  const b6 = 8.5;
  add('B-6', [T, W, b6], [inn, W / 2, -(slotHalf + b6 / 2)], 3, { from: fromInside });
  add('B-6', [T, W, b6], [inn, W / 2, slotHalf + b6 / 2], 3, { from: fromInside });
  add('B-6', [T, b6, W], [inn, W + b6 / 2, -zPost], 3, { from: fromInside });
  add('B-6', [T, b6, W], [inn, W + b6 / 2, zPost], 3, { from: fromInside });
}

// step 4 — B-2 on edge in the slots at the base
add('B-2', [45, W, T], [0, W / 2, 0], 4);

// steps 5 and 6 — the five B-1 top boards; 5 x 3.5 = 17.5, so four 1/4" gaps
const gap = (DEPTH - 5 * W) / 4;
const zs = [0, 1, 2, 3, 4].map((i) => -DEPTH / 2 + W / 2 + i * (W + gap));
const yTop = FRAME_H + T / 2;
for (const i of [0, 4]) add('B-1', [LENGTH, T, W], [0, yTop, zs[i]], 5);
for (const i of [1, 2, 3]) add('B-1', [LENGTH, T, W], [0, yTop, zs[i]], 6);

for (const p of parts) {
  p.size = p.size.map(r);
  p.position = p.position.map(r);
}

const model = {
  slug: 'bench-4',
  units: 'in',
  bounds: { length: LENGTH, width: DEPTH, height: FRAME_H + T },
  view: { azimuthDeg: -38, elevationDeg: 26 },
  notes: [
    'Generated by scripts/guide-models/bench-4.mjs — edit the script, not this file.',
    'End frames: the B-4/B-5 layer faces out, the B-3/B-6 layer faces in; B-2 sits on edge in the 1.5" slot between the bottom B-6 pair (PDF steps 3-4).',
    'Top: five 3.5" B-1 boards over 18.5" leave four 1/4" gaps (PDF step 6: "equal gaps").',
    'Screws are not modelled.',
  ],
  parts,
};

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, '../../src/data/guides/models/bench-4.json');
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, JSON.stringify(model, null, 2) + '\n');
console.log(`wrote ${out}: ${parts.length} parts`);
